name: ✏️ 글 작성
description: 글 작성
title: "[블로그 글 작성]: "
body:
  - type: input
    id: content
    attributes:
      label: 제목
      description: 작성할 글의 내용을 간단히 적어주세요.
      placeholder: ex) Docusaurus 이용하여 팀 블로그 만들기
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 종류
      description: 작성할 글 종류를 선택해주세요.
      options:
        - 공통
        - 백엔드
        - 안드로이드
    validations:
      required: false